### ISSUE TITLE
Dirichlet Flow Matching Project License

### ISSUE THREAD

**Issue by jlotthammer** [HannesStark/dirichlet-flow-matching#3]
Hi, Hannes. 

I'm still working through the paper but I wanted to say very cool work! albeit a bit conceptually dense 😄. I was interested in fiddling around a bit with your code, but I didn't see any license for the project. Is this project fully open source? If so, I recommend adding a permissive license for your project. [I can highly suggest the [MIT license](https://opensource.org/license/mit/)] or a similarly permissive license. See [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) for details on adding a license to the project.

Please let me know.

Thanks in advance!

**Comment by HannesStark** [comment]
Done, thanks for the reminder!

**Comment by jlotthammer** [comment]
Thanks Hannes!
